Add Support for Predictive Scaling
PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-SPD-Interpreter pull request #49
Opened 2024-09-25 17:38 UTC by berbjs

This PR implements things needed for the model changes proposed in PalladioSimulator/Palladio-Addons-SPD-Metamodel#32, notably:
- For the newly introduced ModelBasedScalingPolicies:
	- Adds interpreters/switches for the new SPD metamodel objects (`ModelInterpreter` for the model, which returns the correct `ModelEvaluator`), modifies the `SpdInterpreter` to support the new `ModelBasedScalingPolicy` and the changed `ReactiveScalingPolicy`
	- Adds the `ModelBasedTriggerChecker` which receives `MeasurementMade` and `RepeatedSimulationTimeReached` events and uses a `ModelEvaluator` to decide whether a scaling action should happen (a more detailed EPC diagram is given below)
	- A `RepeatedSimulationTimeReached` event is added that repeats in some given interval and is used by `Model`s to perform periodic operations such as scaling decisions. This event is re-scheduled by a new listener called RepeatedSimulationTimeRepeater
	- The SpdAdjustmentBehavior is changed to support Model-based scaling policies: For each (changed) transformation, a new configuration needs to be stored in the reconfigurator model cache
- Reformatting of some code to fit the Palladio code style (at least as suggested by my Eclipse IDE) → this leads to the relatively large changes in some files
- Add a `RateOfChangeAggregation` that performs a regression (using `org.apache.commons.math3.stat.regression`) to find out the rate of change, requiring a change of the aggregator data structure to DataPoints that contain both the value and the time of the stimulus output that is being aggregated

The `ModelEvaluators` for the different Models will be implemented in separate PRs (the current progress can be found in my fork) as this is already a quite large PR.

Finally, here's an EPC depicting the interaction between `MeasurementMade`/`RepeatedSimulationTimeReached` events and `ModelAdjustmentRequested` events based on the constructs added for the newly introduced `ModelBasedScalingPolicy`: 
![EPC-Eventflow-simplified](https://github.com/user-attachments/assets/3d4e5187-92e8-48c7-b84b-b4c70c7129db)

2025-02-04 16:14 UTC, klinakuf requested changes
@berbjs are some commits missing? The code does not compile while some classes are not resolvable. I guess there is a mismatch between the state of this PR and https://github.com/PalladioSimulator/Palladio-Addons-SPD-Metamodel/pull/32.

To reproduce I fetched both PRs in my local machine and the compilation issues can be detected.

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/ModelInterpreter.java
> +import org.palladiosimulator.spd.models.FuzzyQLearningModel;
not resolvable

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/ModelInterpreter.java
> +import org.palladiosimulator.spd.models.FuzzySARSAModel;
not resolvable

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/SpdInterpreter.java
> +import org.palladiosimulator.spd.TriggerBasedScalingPolicy;
not resolvable

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/entity/aggregator/SlidingTimeWindowAggregation.java
> +        case PERCENTILE90 -> new SlidingTimeWindowAggregation(winSizeSeconds, noEmitDuration,
PERCENTILE90 not resolvable

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/entity/constraint/ThrashingConstraintFilter.java
> +import org.palladiosimulator.spd.TriggerBasedScalingPolicy;
Not resolvable

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/entity/model/AbstractFuzzyLearningModelEvaluator.java
> +import org.palladiosimulator.spd.models.FuzzyLearningModel;
not resolvable

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/entity/model/AbstractFuzzyLearningModelEvaluator.java
> +import org.palladiosimulator.spd.models.InitializationType;
not resolvable

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/entity/model/FuzzyQLearningModelEvaluator.java
> +import org.palladiosimulator.spd.models.FuzzyQLearningModel;
Not resolvable

2025-02-04 16:14 UTC, klinakuf commented on bundles/org.palladiosimulator.analyzer.slingshot.behavior.spd/src/org/palladiosimulator/analyzer/slingshot/behavior/spd/interpreter/entity/model/FuzzySARSAModelEvaluator.java
> +import org.palladiosimulator.spd.models.FuzzySARSAModel;
not resolvable

2025-02-05 14:43 UTC, berbjs commented
@klinakuf Sorry, forgot to update the other PR. I added the missing commits (they were contained in a different branch), this should resolve the compilation issues (at least it did in my testing).

2025-02-06 09:32 UTC, klinakuf commented
**1st Test with the Model in the Zenodo Repository** https://zenodo.org/records/14276724 
- [x] One single **well-formed** SPD Semantic.
- [x] SPD consists of three trigger based policies and two model based policies.
- [x] Tested the Trigger based policy that spins up 5 resource containers.
- [x] Tested the Model-based Fuzzy Q-Learning
- [x] Tested the Model-based Fuzzy Q-Learning with cooldown appllied of 60 seconds

Number of resource containers with Fuzzy Q-Learning (blue) vs. Fuzzy Q-Learning + 60secs cooldown (red).
![Screenshot 2025-02-06 at 10 24 00](https://github.com/user-attachments/assets/f65d1ba3-7afb-42d6-b744-5790c5df1a78)

2025-04-07 17:37 UTC, berbjs commented
Moved to PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-Elasticity#1 in order to contain the breaking changes in this PR and subsequent PRs in a new repository for further testing

2025-04-07 17:37 UTC, closed without merging